=== pkalamucki/GHG-KK/utils/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="1.0">


	<xs:element name="StrategyRoot" type="StrategyRoot" />

	<xs:complexType name="StrategyRoot">
		<xs:sequence>
			<xs:element name="Pack" type="Pack"  minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>			
	</xs:complexType>
	
	<xs:complexType name="Pack">
		<xs:sequence>
			<xs:element name="Agent" type="xs:string" maxOccurs="1"/>
			<xs:element name="Strategy" type="Strategy" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>		
			
	<xs:complexType name="Strategy" abstract="true">		
		<xs:sequence>
			<xs:element name="strategyName" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ZIP">
		<xs:complexContent>
            <xs:extension base="Strategy">
				<xs:sequence>
					<xs:element name="BetaMin" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="BetaMax" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="MarginStartMin" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="MarginStartMax" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="GammaMin" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="GammaMax" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="ConstraintA" type="xs:double" minOccurs="1" maxOccurs="1" />
					<xs:element name="ConstraintB" type="xs:double" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
        </xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ZIP60">
		<xs:complexContent>
            <xs:extension base="Strategy">
				<xs:sequence>
					<xs:element name="Parameter" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
        </xs:complexContent>
	</xs:complexType>

</xs:schema>

=== pkalamucki/GHG-KK/utils/strategie.xml
<?xml version="1.0" encoding="UTF-8"?>

<StrategyRoot
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd">
	<Pack>
		<Agent>CANZ</Agent>
		<Strategy xsi:type="ZIP">
			<strategyName>CANZStrategia1</strategyName>
			<BetaMin>0.2</BetaMin>
			<BetaMax>0.3</BetaMax>
			<MarginStartMin>0.25</MarginStartMin>
			<MarginStartMax>0.35</MarginStartMax>
			<GammaMin>0.1</GammaMin>
			<GammaMax>0.2</GammaMax>
			<ConstraintA>0.198</ConstraintA>
			<ConstraintB>0.16</ConstraintB>
		</Strategy>
	</Pack>
	<Pack>
		<Agent>USA</Agent>
		<Strategy xsi:type="ZIP">
			<strategyName>USAStrategia1</strategyName>
			<BetaMin>0.2</BetaMin>
			<BetaMax>0.3</BetaMax>
			<MarginStartMin>0.25</MarginStartMin>
			<MarginStartMax>0.35</MarginStartMax>
			<GammaMin>0.1</GammaMin>
			<GammaMax>0.2</GammaMax>
			<ConstraintA>0.198</ConstraintA>
			<ConstraintB>0.16</ConstraintB>
		</Strategy>
	</Pack>
	<Pack>
		<Agent>EU</Agent>
		<Strategy xsi:type="ZIP">
			<strategyName>EUStrategia1</strategyName>
			<BetaMin>0.2</BetaMin>
			<BetaMax>0.3</BetaMax>
			<MarginStartMin>0.25</MarginStartMin>
			<MarginStartMax>0.35</MarginStartMax>
			<GammaMin>0.1</GammaMin>
			<GammaMax>0.2</GammaMax>
			<ConstraintA>0.198</ConstraintA>
			<ConstraintB>0.16</ConstraintB>
		</Strategy>
	</Pack>
	<Pack>
		<Agent>WNP</Agent>
		<Strategy xsi:type="ZIP">
			<strategyName>WNPStrategia1</strategyName>
			<BetaMin>0.2</BetaMin>
			<BetaMax>0.3</BetaMax>
			<MarginStartMin>0.25</MarginStartMin>
			<MarginStartMax>0.35</MarginStartMax>
			<GammaMin>0.1</GammaMin>
			<GammaMax>0.2</GammaMax>
			<ConstraintA>0.198</ConstraintA>
			<ConstraintB>0.16</ConstraintB>
		</Strategy>
	</Pack>
	<Pack>
		<Agent>Japonia</Agent>
		<Strategy xsi:type="ZIP">
			<strategyName>JaponiaStrategia1</strategyName>
			<BetaMin>0.2</BetaMin>
			<BetaMax>0.3</BetaMax>
			<MarginStartMin>0.25</MarginStartMin>
			<MarginStartMax>0.35</MarginStartMax>
			<GammaMin>0.1</GammaMin>
			<GammaMax>0.2</GammaMax>
			<ConstraintA>0.198</ConstraintA>
			<ConstraintB>0.16</ConstraintB>
		</Strategy>
	</Pack>
</StrategyRoot>
